using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SentezEInvoiceXML {
    public class Erp_Invoice {
        public int RecId { get; set; }
        public int CompanyId { get; set; }
        public object WorkplaceId { get; set; }
        public int ReceiptType { get; set; }
        public string ReceiptNo { get; set; }
        public object ReceiptSubType { get; set; }
        public DateTime ReceiptDate { get; set; }
        public DateTime ReceiptTime { get; set; }
        public string DocumentNo { get; set; }
        public int CurrentAccountId { get; set; }
        public int AddressId { get; set; }
        public object ShipToCurrentAccountId { get; set; }
        public object ShipToAddressId { get; set; }
        public object PaymentToCurrentAccountId { get; set; }
        public object InWarehouseId { get; set; }
        public int OutWarehouseId { get; set; }
        public object CostCenterId { get; set; }
        public object DealerId { get; set; }
        public object CustomerId { get; set; }
        public object CustomerAddressId { get; set; }
        public object BrokerId { get; set; }
        public object ManufacturerId { get; set; }
        public object PaymentPlanId { get; set; }
        public object CustomerOrderNo { get; set; }
        public object SpecialCode { get; set; }
        public object AccessCode { get; set; }
        public object ProjectId { get; set; }
        public object EmployeeId { get; set; }
        public object ContactId { get; set; }
        public object CashId { get; set; }
        public object TransporterId { get; set; }
        public object VehicleId { get; set; }
        public int HasNegativeEffect { get; set; }
        public object Explanation { get; set; }
        public object GpsXCoordinate { get; set; }
        public object GpsYCoordinate { get; set; }
        public DateTime TermDate { get; set; }
        public int IsTaxExempted { get; set; }
        public object IsManualVat { get; set; }
        public object IsManuelWithholding { get; set; }
        public object Bonus { get; set; }
        public object RoundingAmount { get; set; }
        public object WithholdingFactor { get; set; }
        public object WithholdingDivisor { get; set; }
        public object Rate1 { get; set; }
        public object Rate2 { get; set; }
        public object Rate3 { get; set; }
        public object Rate4 { get; set; }
        public object Rate5 { get; set; }
        public float SubTotal { get; set; }
        public float VatAmount { get; set; }
        public float WithholdingAmount1 { get; set; }
        public float WithholdingAmount2 { get; set; }
        public int WithholdingType { get; set; }
        public float Rate1Amount { get; set; }
        public float Rate2Amount { get; set; }
        public float Rate3Amount { get; set; }
        public float Rate4Amount { get; set; }
        public float Rate5Amount { get; set; }
        public float ExciseTaxAmount { get; set; }
        public float CommunicationTaxAmount { get; set; }
        public float DistributedDiscountsTotal { get; set; }
        public float DiscountsTotal { get; set; }
        public float DiscountsTotalGross { get; set; }
        public float DistributedExpensesTotal { get; set; }
        public float ExpensesTotal { get; set; }
        public float GrandTotal { get; set; }
        public object ForexId { get; set; }
        public float ForexRate { get; set; }
        public float SubTotalForex { get; set; }
        public float VatAmountForex { get; set; }
        public float WithholdingAmount1Forex { get; set; }
        public float WithholdingAmount2Forex { get; set; }
        public float Rate1AmountForex { get; set; }
        public float Rate2AmountForex { get; set; }
        public float Rate3AmountForex { get; set; }
        public float Rate4AmountForex { get; set; }
        public float Rate5AmountForex { get; set; }
        public float ExciseTaxAmountForex { get; set; }
        public float CommunicationTaxAmountForex { get; set; }
        public float DistributedDiscountsTotalForex { get; set; }
        public float DiscountsTotalForex { get; set; }
        public float DiscountsTotalGrossForex { get; set; }
        public float DistributedExpensesTotalForex { get; set; }
        public float ExpensesTotalForex { get; set; }
        public float GrandTotalForex { get; set; }
        public int InventoryReceiptId { get; set; }
        public object WorkOrderReceiptId { get; set; }
        public object GLReceiptId { get; set; }
        public int CurrentAccountReceiptId { get; set; }
        public object CustomerTransactionId { get; set; }
        public object DischargeDate { get; set; }
        public int IsEximReceipt { get; set; }
        public int IsForexReceipt { get; set; }
        public int IsBrokerageInvoice { get; set; }
        public int IsExportRegistered { get; set; }
        public object IsPrinted { get; set; }
        public object PageCount { get; set; }
        public object BlockedAmount { get; set; }
        public object IsChecked { get; set; }
        public int IsApproved { get; set; }
        public object ApprovedAt { get; set; }
        public object ApprovedBy { get; set; }
        public object IsLocked { get; set; }
        public object LockedAt { get; set; }
        public object LockedBy { get; set; }
        public int ControlCode { get; set; }
        public int NotForPaymentPlan { get; set; }
        public object IsClosed { get; set; }
        public int IsCancelled { get; set; }
        public object CancelledAt { get; set; }
        public object CancelledBy { get; set; }
        public object IsETrade { get; set; }
        public int IsEInvoice { get; set; }
        public int IsESendMail { get; set; }
        public int EInvoiceScenario { get; set; }
        public int EInvoiceStatus { get; set; }
        public object EInvoicePeriodStart { get; set; }
        public object EInvoicePeriodEnd { get; set; }
        public object EInvoiceGuid { get; set; }
        public object EInvoiceNo { get; set; }
        public object EInvoiceTaxTypeCode { get; set; }
        public object EInvoiceTaxExemptionReasonCode { get; set; }
        public string EArchivesShippingType { get; set; }
        public object EArchivesSummaryValue { get; set; }
        public object EArchivesInstallationNo { get; set; }
        public object EArchivesWebAddress { get; set; }
        public object EArchivesPaymentType { get; set; }
        public object EArchivesPaymentTypeOtherExp { get; set; }
        public DateTime EArchivesSendDate { get; set; }
        public object EArchivesCargoId { get; set; }
        public object CustomsCurrentAccountId { get; set; }
        public object PosReceiptId { get; set; }
        public object CreditCardReceiptId { get; set; }
        public object VatListField01 { get; set; }
        public object VatListField02 { get; set; }
        public object VatListField03 { get; set; }
        public object VatListField04 { get; set; }
        public object VatListField05 { get; set; }
        public object SgkDocumentNo { get; set; }
        public object ReturnOperationType { get; set; }
        public object ExportImportType { get; set; }
        public object PaymentType { get; set; }
        public object DeliveryType { get; set; }
        public object PackageType { get; set; }
        public object PackageMark { get; set; }
        public object PackagingNo { get; set; }
        public object TransportType { get; set; }
        public object IsFreeOfCharge { get; set; }
        public DateTime InsertedAt { get; set; }
        public int InsertedBy { get; set; }
        public DateTime UpdatedAt { get; set; }
        public int UpdatedBy { get; set; }
        public int IsDeleted { get; set; }
        public object DeletedAt { get; set; }
        public object DeletedBy { get; set; }
        public object UniqueId { get; set; }
        public int IsForexEInvoice { get; set; }
        public object UD_EInvoiceIntegratorInvoiceId { get; set; }
        public object BankCreditItemId { get; set; }
        public object IsLeasing { get; set; }
        public object ApprovedExplanation { get; set; }
        public float SubTotalVatIncluded { get; set; }
        public float SubTotalVatIncludedForex { get; set; }
        public float DiscountsTotalVatIncluded { get; set; }
        public float DiscountsTotalVatIncludedForex { get; set; }
        public object DistributedDiscountsTotalVatIncluded { get; set; }
        public object DistributedDiscountsTotalVatIncludedForex { get; set; }
        public float VatAmountAccommodation { get; set; }
        public float VatAmountAccommodationForex { get; set; }
        public object IsSpecialBase { get; set; }
        public object CancelledExplanation { get; set; }
    }

}
