using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SentezEInvoiceXML {
    public class Erp_CurrentAccount {
        public int RecId { get; set; }
        public int CompanyId { get; set; }
        public string CurrentAccountCode { get; set; }
        public string CurrentAccountName { get; set; }
        public int CurrentAccountType { get; set; }
        public int CurrentAccountKind { get; set; }
        public int CategoryId { get; set; }
        public object SectorId { get; set; }
        public object TradingGroupId { get; set; }
        public object GroupId { get; set; }
        public string TradeName { get; set; }
        public object AccessCode { get; set; }
        public object SpecialCode { get; set; }
        public object ForexRateId { get; set; }
        public object ForexId { get; set; }
        public string EMail { get; set; }
        public object WebAddress { get; set; }
        public object WebContent { get; set; }
        public object Blog { get; set; }
        public object Facebook { get; set; }
        public object Twitter { get; set; }
        public object ParentId { get; set; }
        public object BrokerId { get; set; }
        public object PaymentType { get; set; }
        public object StatusId { get; set; }
        public object IsBlackList { get; set; }
        public object IsVip { get; set; }
        public object IsFrequent { get; set; }
        public object IsPotential { get; set; }
        public object IsDealer { get; set; }
        public object IsAgent { get; set; }
        public object CardNo { get; set; }
        public object IsCardActive { get; set; }
        public object TaxOfficeId { get; set; }
        public string TaxNo { get; set; }
        public object EmployeeId { get; set; }
        public object SellerId { get; set; }
        public object CustomerGLAccountId { get; set; }
        public object SupplierGLAccountId { get; set; }
        public object TermDay { get; set; }
        public object VisitPeriodType { get; set; }
        public object VisitPeriod { get; set; }
        public object VisitDays { get; set; }
        public object InterestRate { get; set; }
        public object DiscountGroupCode { get; set; }
        public object PriceGroupCode { get; set; }
        public object SalesDiscountId { get; set; }
        public object PurchaseDiscountId { get; set; }
        public object RiskLimit { get; set; }
        public object ChequeRiskLimit { get; set; }
        public object EndorsmentChequeRiskLimit { get; set; }
        public object NoteRiskLimit { get; set; }
        public object EndorsmentNoteRiskLimit { get; set; }
        public object ChequeRiskFactor { get; set; }
        public object NoteRiskFactor { get; set; }
        public object RiskTypeCheque { get; set; }
        public object RiskTypeEndorsmentCheque { get; set; }
        public object RiskType { get; set; }
        public object RiskOver { get; set; }
        public object OrderRiskOver { get; set; }
        public object DispatchRiskOver { get; set; }
        public object ChequeRiskOver { get; set; }
        public object WarehouseId { get; set; }
        public object CostCenterId { get; set; }
        public object ShipmentType { get; set; }
        public object IsPartialShipment { get; set; }
        public object MinShipmentRate { get; set; }
        public object TransporterId { get; set; }
        public object BankId { get; set; }
        public object PaymentPlanId { get; set; }
        public object EducationType { get; set; }
        public object MaritalStatus { get; set; }
        public object IdType { get; set; }
        public object IdCardNo { get; set; }
        public object IdNo { get; set; }
        public object IdFathersName { get; set; }
        public object IdMothersName { get; set; }
        public object IdCity { get; set; }
        public object IdDistrict { get; set; }
        public object IdMahalle { get; set; }
        public object IdKoy { get; set; }
        public object IdCilt { get; set; }
        public object IdSayfa { get; set; }
        public object IdKutuk { get; set; }
        public object IdIssuedPlace { get; set; }
        public object IdIssuedDate { get; set; }
        public object SocialSecurityNo { get; set; }
        public object Gender { get; set; }
        public object BirthDate { get; set; }
        public object BirthPlace { get; set; }
        public object CompanyName { get; set; }
        public object JobTitle { get; set; }
        public string Profession { get; set; }
        public string GsmPhone { get; set; }
        public object MariageDate { get; set; }
        public object SpouseName { get; set; }
        public object SpouseBirthDate { get; set; }
        public object SpouseCompany { get; set; }
        public object SpouseJobTitle { get; set; }
        public object SpouseProfession { get; set; }
        public object SymbolId { get; set; }
        public object IsEAgreement { get; set; }
        public object IsEInvoice { get; set; }
        public object EInvoiceScenario { get; set; }
        public object EInvoiceAlias { get; set; }
        public object NationalityId { get; set; }
        public object MarketId { get; set; }
        public object ForegroundColor { get; set; }
        public object BackgroundColor { get; set; }
        public object NotForPaymentPlan { get; set; }
        public object PaymentPlanDebit { get; set; }
        public object PaymentPlanDebitForexId { get; set; }
        public object LastPaymentDayPeriod { get; set; }
        public object ValuationAmount { get; set; }
        public object IsForex { get; set; }
        public object IsProducer { get; set; }
        public int InUse { get; set; }
        public object PassportNo { get; set; }
        public object PassportIssueDate { get; set; }
        public object IsLocked { get; set; }
        public object LockedAt { get; set; }
        public object LockedBy { get; set; }
        public DateTime InsertedAt { get; set; }
        public int InsertedBy { get; set; }
        public object UpdatedAt { get; set; }
        public object UpdatedBy { get; set; }
        public object IsDeleted { get; set; }
        public object DeletedAt { get; set; }
        public object DeletedBy { get; set; }
        public object IsRiskControl { get; set; }
        public object NaceCode { get; set; }
        public object MersisNo { get; set; }
        public object TradeRegistrationNo { get; set; }
        public object IsEDespatch { get; set; }
        public object EArchivesShippingType { get; set; }
        public object WorkplaceId { get; set; }
    }

}
