using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SentezEInvoiceXML {
    public class Erp_InventoryReceipt {
        public int RecId { get; set; }
        public int CompanyId { get; set; }
        public int WorkplaceId { get; set; }
        public object ReceiptUpType { get; set; }
        public int ReceiptType { get; set; }
        public string ReceiptNo { get; set; }
        public int ReceiptSubType { get; set; }
        public DateTime ReceiptDate { get; set; }
        public DateTime ReceiptTime { get; set; }
        public object TermDate { get; set; }
        public object DocumentNo { get; set; }
        public int CurrentAccountId { get; set; }
        public object AddressId { get; set; }
        public object ShipToCurrentAccountId { get; set; }
        public object ShipToAddressId { get; set; }
        public object InWarehouseId { get; set; }
        public int OutWarehouseId { get; set; }
        public object ConsumptionWarehouseId { get; set; }
        public object CostCenterId { get; set; }
        public object DealerId { get; set; }
        public object CustomerId { get; set; }
        public object CustomerAddressId { get; set; }
        public object PaymentPlanId { get; set; }
        public object CustomerOrderNo { get; set; }
        public object SpecialCode { get; set; }
        public object AccessCode { get; set; }
        public object ProjectId { get; set; }
        public int EmployeeId { get; set; }
        public object ContactId { get; set; }
        public object CashId { get; set; }
        public object TransporterId { get; set; }
        public object VehicleId { get; set; }
        public object HasNegativeEffect { get; set; }
        public int ComplimentaryType { get; set; }
        public object Explanation { get; set; }
        public object GpsXCoordinate { get; set; }
        public object GpsYCoordinate { get; set; }
        public int IsTaxExempted { get; set; }
        public object WithholdingFactor { get; set; }
        public object WithholdingDivisor { get; set; }
        public object Rate1 { get; set; }
        public object Rate2 { get; set; }
        public object Rate3 { get; set; }
        public object Rate4 { get; set; }
        public object Rate5 { get; set; }
        public float SubTotal { get; set; }
        public float VatAmount { get; set; }
        public float WithholdingAmount1 { get; set; }
        public float WithholdingAmount2 { get; set; }
        public object WithholdingType { get; set; }
        public float Rate1Amount { get; set; }
        public float Rate2Amount { get; set; }
        public float Rate3Amount { get; set; }
        public float Rate4Amount { get; set; }
        public float Rate5Amount { get; set; }
        public float ExciseTaxAmount { get; set; }
        public float CommunicationTaxAmount { get; set; }
        public float DistributedDiscountsTotal { get; set; }
        public float DiscountsTotal { get; set; }
        public float DiscountsTotalGross { get; set; }
        public float DistributedExpensesTotal { get; set; }
        public float ExpensesTotal { get; set; }
        public float GrandTotal { get; set; }
        public object ForexId { get; set; }
        public object ForexRate { get; set; }
        public float SubTotalForex { get; set; }
        public float VatAmountForex { get; set; }
        public float WithholdingAmount1Forex { get; set; }
        public float WithholdingAmount2Forex { get; set; }
        public float Rate1AmountForex { get; set; }
        public float Rate2AmountForex { get; set; }
        public float Rate3AmountForex { get; set; }
        public float Rate4AmountForex { get; set; }
        public float Rate5AmountForex { get; set; }
        public float ExciseTaxAmountForex { get; set; }
        public float CommunicationTaxAmountForex { get; set; }
        public float DistributedDiscountsTotalForex { get; set; }
        public float DiscountsTotalForex { get; set; }
        public float DiscountsTotalGrossForex { get; set; }
        public float DistributedExpensesTotalForex { get; set; }
        public float ExpensesTotalForex { get; set; }
        public float GrandTotalForex { get; set; }
        public int PosReceiptId { get; set; }
        public object Receipt99Id { get; set; }
        public object Receipt101Id { get; set; }
        public object ManufactureReceiptId { get; set; }
        public object ConsumptionReceiptId { get; set; }
        public object WasteReceiptId { get; set; }
        public object TransferInflowReceiptId { get; set; }
        public object WorkOrderReceiptId { get; set; }
        public object InvoiceId { get; set; }
        public object GLReceiptId { get; set; }
        public object CurrentAccountReceiptId { get; set; }
        public object CustomerTransactionId { get; set; }
        public object ShipmentReceiptId { get; set; }
        public object ShipmentDate { get; set; }
        public object IsEximReceipt { get; set; }
        public object IsForexReceipt { get; set; }
        public object IsPrinted { get; set; }
        public object PageCount { get; set; }
        public object IsChecked { get; set; }
        public int IsApproved { get; set; }
        public object ApprovedAt { get; set; }
        public object ApprovedBy { get; set; }
        public object IsLocked { get; set; }
        public object LockedAt { get; set; }
        public object LockedBy { get; set; }
        public int ControlCode { get; set; }
        public object IsClosed { get; set; }
        public object IsCancelled { get; set; }
        public DateTime InsertedAt { get; set; }
        public int InsertedBy { get; set; }
        public DateTime UpdatedAt { get; set; }
        public int UpdatedBy { get; set; }
        public int IsDeleted { get; set; }
        public object DeletedAt { get; set; }
        public object DeletedBy { get; set; }
        public object UniqueId { get; set; }
        public object OrderIdFromWeb { get; set; }
        public object ApprovedExplanation { get; set; }
        public object OrderNote { get; set; }
        public object IsEDespatch { get; set; }
        public object IsForexEDespatch { get; set; }
        public object IsESendMail { get; set; }
        public object EDespatchStatus { get; set; }
        public object EDespatchGuid { get; set; }
        public object EDespatchNo { get; set; }
        public object EDespatchScenario { get; set; }
        public object ShipmentTime { get; set; }
        public object EDespatchIntegratorId { get; set; }
        public object EDespatchAdviceType { get; set; }
        public object DespatchContactId { get; set; }
        public object IsTransportReceipt { get; set; }
        public float SubTotalVatIncluded { get; set; }
        public float SubTotalVatIncludedForex { get; set; }
        public float DiscountsTotalVatIncluded { get; set; }
        public float DiscountsTotalVatIncludedForex { get; set; }
        public float DistributedDiscountsTotalVatIncluded { get; set; }
        public float DistributedDiscountsTotalVatIncludedForex { get; set; }
        public float VatAmountAccommodation { get; set; }
        public float VatAmountAccommodationForex { get; set; }
        public object CancelledExplanation { get; set; }
    }

}
